apiVersion: apps/v1
kind: Deployment
metadata:
  name: uda-fe
  labels:
    app: uda-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uda-fe
  template:
    metadata:
      labels:
        app: uda-fe
    spec:
      containers:
        - name: uda-fe
          image: uda-fe
          ports:
            - containerPort: 3000
