apiVersion: v1
kind: Service
metadata:
  name: uda-fe-service
  labels:
    app: uda-fe-service
spec:
  type: LoadBalancer
  selector:
    app: uda-fe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
