apiVersion: apps/v1
kind: Deployment
metadata:
  name: uda-be
  labels:
    app: uda-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uda-be
  template:
    metadata:
      labels:
        app: uda-be
    spec:
      containers:
        - name: uda-be
          image: uda-be
          ports:
            - containerPort: 5000
