apiVersion: v1
kind: Service
metadata:
  name: uda-be-service
  labels:
    app: uda-be-service
spec:
  type: LoadBalancer
  selector:
    app: uda-be
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
