version: 0.2

phases:
  pre_build:
    commands:
      - echo "Loging in to ECR"
      # - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 811777786649.dkr.ecr.us-west-2.amazonaws.com

  build:
    commands:
      - echo "Build image"
      # - docker build -t 811777786649.dkr.ecr.us-west-2.amazonaws.com/udacity-analytics-app:v1 .

  post_build:
    commands:
      - echo "Push image"
      # - docker push 811777786649.dkr.ecr.us-west-2.amazonaws.com/udacity-analytics-app:v1
