name: Build and deploy backend

env:
  APP_NAME: Udacity Backend
  IMAGE_TAG: udacity-4st-project-be:v1
  SRC_DIR: src/backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup python3
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Update package
        run: | 
              sudo apt update && \
              sudo apt install \
              && python -m pip install flake8 \
              && pip3 install pipenv

      - name: Install dependencies
        working-directory: ${{ env.SRC_DIR }}
        run: pipenv install

      - name: Test (simulate a failure)
        working-directory: ${{ env.SRC_DIR }}
        run: pipenv run test

      - name: Lint
        working-directory: ${{ env.SRC_DIR }}
        run: pipenv run lint

  build:
    runs-on: ubuntu-latest
    needs: tests
    if: ${{ failure() == false }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        run: |
          docker buildx build --platform linux/amd64 --tag ${{ env.IMAGE_TAG }} ./${{ env.SRC_DIR }}
