name: Build and deploy backend

env:
  APP_NAME: Udacity Backend
  IMAGE_TAG: udacity-4st-project-be:v1

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        run: |
          docker buildx build --platform linux/amd64 --tag $IMAGE_TAG ./src/backend
