name: Backend CD

env:
  APP_NAME: Udacity Backend
  IMAGE_TAG: 267769458268.dkr.ecr.us-east-1.amazonaws.com/backend:${GITHUB_SHA::7}
  SRC_DIR: src/backend
  DOCKER_URL: 267769458268.dkr.ecr.us-east-1.amazonaws.com
  AWS_REGION: us-east-1
  EKS_CLUSTER: cluster

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup python3
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Update package
        run: |
          sudo apt update && \
          sudo apt install \
          && python -m pip install flake8 \
          && pip3 install pipenv

      - name: Install dependencies
        working-directory: ${{ env.SRC_DIR }}
        run: pipenv install

      - name: Lint
        working-directory: ${{ env.SRC_DIR }}
        run: pipenv run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup python3
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Update package
        run: |
          sudo apt update && \
          sudo apt install \
          && python -m pip install flake8 \
          && pip3 install pipenv

      - name: Install dependencies
        working-directory: ${{ env.SRC_DIR }}
        run: pipenv install

      - name: Test
        working-directory: ${{ env.SRC_DIR }}
        run: pipenv run test

  build:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    if: ${{ failure() == false }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup python3
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Update package
        run: |
          sudo apt update && \
          sudo apt install \
          && python -m pip install flake8 \
          && pip3 install pipenv

      - name: Install dependencies
        working-directory: ${{ env.SRC_DIR }}
        run: pipenv install

      - name: Test
        working-directory: ${{ env.SRC_DIR }}
        run: pipenv run test

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          #aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}
          aws configure set default.region $AWS_REGION

      - name: Log in to Docker Hub
        run: aws ecr get-login-password --region $AWS_REGION --profile default | docker login --username AWS --password-stdin $DOCKER_URL

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & push backend image
        run: |
          docker buildx build --platform linux/amd64 --tag ${{ env.IMAGE_TAG }} --push ./${{ env.SRC_DIR }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ failure() == false }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"
          install-missing-components: true

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}
          aws configure set default.region $AWS_REGION

      - name: Configure kubectl
        run: |
          mkdir -p ~/.kube
          aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER

      - name: deploy backend
        run: |
          cd $SRC_DIR/k8s
          kustomize edit set image IMAGE_TAG=${{ env.IMAGE_TAG }}
          kustomize build | kubectl apply -f -
