name: Build and deploy frontend

env:
  APP_NAME: Udacity Frontend
  IMAGE_TAG: udacity-4st-project-fe:v1
  REACT_APP_MOVIE_API_URL: http://uda-be-service

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build frontend image
        run: |
          docker buildx build --platform linux/amd64 --tag $IMAGE_TAG ./src/frontend
