name: Build and deploy frontend

env:
  APP_NAME: Udacity Frontend
  IMAGE_TAG: udacity-4st-project-fe:v1
  REACT_APP_MOVIE_API_URL: http://uda-be-service
  SRC_DIR: src/frontend

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        working-directory: ${{ env.SRC_DIR }}
        run: npm install

      - name: Test
        working-directory: ${{ env.SRC_DIR }}
        run: npm test

      - name: Lint
        working-directory: ${{ env.SRC_DIR }}
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: tests
    if: ${{ failure() == false }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build frontend image
        run: |
          docker buildx build --build-arg=REACT_APP_MOVIE_API_URL=${{ env.REACT_APP_MOVIE_API_URL }} --platform linux/amd64 --tag ${{ env.IMAGE_TAG }} ./src/frontend
