name: Build and deploy frontend

env:
  APP_NAME: Udacity Frontend
  IMAGE_TAG: 267769458268.dkr.ecr.us-east-1.amazonaws.com/frontend:v1
  REACT_APP_MOVIE_API_URL: http://uda-be-service
  SRC_DIR: src/frontend
  DOCKER_URL: 267769458268.dkr.ecr.us-east-1.amazonaws.com
  AWS_REGION: us-east-1

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        working-directory: ${{ env.SRC_DIR }}
        run: npm install

      - name: Test (simulate a failure)
        working-directory: ${{ env.SRC_DIR }}
        run: npm test

      - name: Lint
        working-directory: ${{ env.SRC_DIR }}
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: tests
    if: ${{ failure() == false }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}
          aws configure set default.region $AWS_REGION


      - name: Log in to Docker Hub
        run: aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $DOCKER_URL

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build frontend image
        run: |
          docker buildx build --build-arg=REACT_APP_MOVIE_API_URL=${{ env.REACT_APP_MOVIE_API_URL }} \
           --platform linux/amd64 \
           --tag ${{ env.IMAGE_TAG }} --push ./${{ env.SRC_DIR }}
